version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SpyderLayerTest"
s3_bucket = "rz-ds-resources"
s3_prefix = "etc/deploy"
region = "eu-west-1"
profile = "rz-robot"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
