AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  first-layer

  Sample SAM Template for first-layer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  Spider2Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Spider2LayeredFunc
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
      Layers:
        - !Ref MyPyLibs

  MyPyLibs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mypy-layer
      Description: Dependencies for the blank sample app.
      ContentUri: lib_zip/python.zip
      CompatibleRuntimes:
        - python3.7
        - python3.6

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  Spider2Function:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt Spider2Function.Arn
  Spider2FunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt Spider2FunctionRole.Arn
